name: Label Issue In Develop
on: 
  pull_request:
    types: [closed]
# solution taken from https://github.com/actions/first-interaction/issues/10#issuecomment-1041402989
# this allows this workflow to label the PRs to have the `in-develop` label
permissions:
  contents: write
  pull-requests: write
jobs:
  label:
    name: Label Issue In Develop
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python v3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/scripts/requirements.txt

      - name: Run in_develop_labeler.py
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: ${{ github.event.pull_request.body }}
        run: python ./.github/scripts/in_develop_labeler.py $TOKEN "$BODY"
